"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true

[palette]
os = "#e0e0e0"
closer = "p:os"
orange = "#FFB347"
lavender = "#FFCC99"
blue = "#FF6B35"
git = "#EA9DFF"

# Start of prompt arrow
[[blocks]]
alignment = "left"
type = "prompt"

# os
[[blocks.segments]]
foreground = "p:os"
style = "plain"
template = "{{.Icon}}  "
type = "os"

# user & host
[[blocks.segments]]
foreground = "p:blue"
style = "plain"
template = "{{ .UserName }}@{{ .HostName }} |"
type = "session"

# Path
[[blocks.segments]]
foreground = "p:orange"
style = "plain"
template = "{{ .Path }} | "
type = "path"


# Home Folder
[blocks.segments.properties]
folder_icon = "..\ue5fe.."
home_icon = "~"
style = "full"

# Git
[[blocks.segments]]
foreground = "p:git"
style = "plain"
template = "{{ .HEAD }} | "
type = "git"







[blocks.segments.properties]
branch_icon = "\ue725 "
cherry_pick_icon = "\ue29b "
commit_icon = "\uf417 "
fetch_status = false
fetch_upstream_icon = false
merge_icon = "\ue727 "
no_commits_icon = "\uf0c3 "
rebase_icon = "\ue728 "
revert_icon = "\uf0e2 "
tag_icon = "\uf412 "

# Bun
[[blocks.segments]]
type = "bun"
style = "plain"
foreground = "p:orange"
template = " {{ .Full }} "

# Go
[[blocks.segments]]
type = "go"
style = "plain"
foreground = "#7FD5EA"
template = " {{ .Full }} "


[[blocks.segments]]
type = "python"
style = "plain"
foreground = "#100e23"
template = "  {{ .Full }} "

#  right prompt
[[blocks]]
alignment = "right"
type = "prompt"

# Time
# [[blocks.segments]]
# type = "time"
# style = "plain"
# foreground = "#007ACC"
#
# [blocks.segments.properties]
# time_format = "15:04:05"

# execution ||
[[blocks.segments]]
foreground = "#ffffff"
style = "plain"
template = " {{ .FormattedMs }} "
type = "executiontime"

[blocks.segments.properties]
threshold = 500
style = "austin"
always_enabled = true


# Shell
# [[blocks.segments]]
# type = "shell"
# style = "plain"
# foreground = "#ffffff"
#




[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
style = "plain"
foreground = "p:closer"
template = "\uf105 "
type = "text"



